export const STANDALONE_PLANS = [
  {
    id: 'go',
    name: 'Go',
    monthlyPriceId: 'price_1TOii0HSoN0LpQiBieTZRrUU',
    annualPriceId: 'price_1TOii0HSoN0LpQiBz9r0nqBz',
    monthlyPrice: 29,
    annualPrice: 290,
    limits: {
      maxSlots: 1,
    },
    features: [
      '1 número de WhatsApp conectado',
      'Mensajes de WhatsApp ilimitados',
      'Bandeja unificada de conversaciones',
      '2 usuarios (tú + 1 colaborador)',
      'Respuestas rápidas ilimitadas',
      'Transcripción automática de audios',
      'Asistente de IA por WhatsApp',
      'Etiquetas y organización de contactos',
    ],
  },
  {
    id: 'flow',
    name: 'Flow',
    monthlyPriceId: 'price_1TOimyHSoN0LpQiB6u9YT6lk',
    annualPriceId: 'price_1TOimyHSoN0LpQiB0pupYGHU',
    monthlyPrice: 97,
    annualPrice: 970,
    limits: {
      maxSlots: 3,
    },
    features: [
      'Incluye todo lo del Go',
      'Hasta 3 números de WhatsApp',
      'Hasta 5 usuarios',
      'CRM completo con pipelines de venta',
      'Automatizaciones avanzadas',
      'Calendario con reservas online',
      'Agentes de IA avanzados',
      'Landing pages y formularios',
      'Reportes de ventas y conversión',
      'Automatiza Facebook e Instagram con IA',
      'Onboarding 1:1 de 60 min con especialista',
      'Acceso a comunidad privada',
    ],
    recommended: true,
  },
  {
    id: 'elite',
    name: 'Elite',
    monthlyPriceId: 'price_1TOithHSoN0LpQiBwp9tadRl',
    annualPriceId: 'price_1TOithHSoN0LpQiBENAvlxHF',
    monthlyPrice: 247,
    annualPrice: 2470,
    limits: {
      maxSlots: 10,
    },
    features: [
      'Incluye todo lo del Flow',
      'Hasta 10 números de WhatsApp',
      'Usuarios ilimitados',
      'Tienda online',
      'Membresías y cursos online',
      'Email marketing incluido',
      'Gestión de reseñas (Google, Facebook)',
      'Reportes avanzados y dashboards',
      'Agentes de voz con IA',
      'Asistente de IA personalizado por tu negocio',
      'Onboarding extendido (3 sesiones de 60 min)',
    ],
  },
];

export const STANDALONE_PRICE_TO_PLAN = {
  price_1TOii0HSoN0LpQiBieTZRrUU: 'go',
  price_1TOii0HSoN0LpQiBz9r0nqBz: 'go',
  price_1TOimyHSoN0LpQiB6u9YT6lk: 'flow',
  price_1TOimyHSoN0LpQiB0pupYGHU: 'flow',
  price_1TOithHSoN0LpQiBwp9tadRl: 'elite',
  price_1TOithHSoN0LpQiBENAvlxHF: 'elite',
};
