import assert from "node:assert";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");

const dashboardPath = path.join(root, "src", "admin", "AgencyDashboard.jsx");
const builderPath = path.join(root, "src", "admin", "OfficialTemplateBuilder.jsx");
const esLocalePath = path.join(root, "src", "locales", "es.js");
const enLocalePath = path.join(root, "src", "locales", "en.js");

const dashboard = fs.readFileSync(dashboardPath, "utf8");
const builder = fs.readFileSync(builderPath, "utf8");
const esLocale = fs.readFileSync(esLocalePath, "utf8");
const enLocale = fs.readFileSync(enLocalePath, "utf8");

assert.match(dashboard, /import OfficialTemplateBuilder from '\.\/OfficialTemplateBuilder'/);
assert.match(dashboard, /id="templates"/);
assert.match(dashboard, /dash\.nav\.templates/);
assert.match(dashboard, /activeTab === 'templates'/);
assert.match(dashboard, /<OfficialTemplateBuilder[\s\S]*locations=\{locations\}[\s\S]*token=\{token\}/);

assert.match(builder, /\/agency\/location-details\/\$\{encodeURIComponent\(locationId\)\}/);
assert.match(builder, /\/agency\/whatsapp-official\/templates\?\$\{query\.toString\(\)\}/);
assert.match(builder, /authFetch\("\/agency\/whatsapp-official\/templates"/);
assert.match(builder, /function isOfficialSlot/);
assert.match(builder, /function isTemplateReadyOfficialSlot/);
assert.match(builder, /\.filter\(isTemplateReadyOfficialSlot\)/);
assert.match(builder, /official\.hasAccessToken/);
assert.match(builder, /if \(!slot\.hasAccessToken\) return;/);
assert.match(builder, /templates\.builder\.loading_slots/);
assert.match(builder, /templateLoadError/);
assert.match(builder, /friendlyTemplateError/);
assert.match(builder, /templates\.builder\.access_lost_title/);
assert.match(builder, /templates\.builder\.access_lost_action_clear/);
assert.match(builder, /translate="no"/);
assert.doesNotMatch(builder, /toast\.error\(t\("templates\.builder\.load_templates_error"\)[\s\S]*description: error\.message/, "template load failures must render a stable in-page diagnostic instead of only a toast");
assert.match(builder, /normalizeTemplateName/);
assert.match(builder, /function extractTemplatePlaceholders/);
assert.match(builder, /function getTemplateCommandPlaceholders/);
assert.match(builder, /valor_\$\{safePlaceholder\}/);
assert.match(builder, /Variables: \{placeholders\.map/);
assert.match(builder, /!\[TPL:\$\{name\}:\$\{language\}/);
assert.match(builder, /groupTemplates/);
assert.match(builder, /GHL_VARIABLE_OPTIONS/);
assert.match(builder, /function buildTemplateCommand\(template = \{\}, fallbackLanguage = "es", variableMappings = \{\}\)/);
assert.match(builder, /getDefaultTemplateValue/);
assert.match(builder, /templateVariableMappings/);
assert.match(builder, /openMappingModal/);
assert.match(builder, /renderVariableMappingModal/);
assert.match(builder, /templates\.builder\.variable_mapper/);
assert.match(builder, /\{\{contact\.first_name\}\}/);
assert.match(builder, /label: "name"/);
assert.match(builder, /groupGhlVariableOptions/);
assert.match(builder, /<optgroup/);
assert.match(builder, /templates\.builder\.selected_ghl_variable/);
assert.match(builder, /<Pencil size=\{14\}/);
assert.match(builder, /selectedSlotKeys/);
assert.match(builder, /toggleSlotSelection/);
assert.match(builder, /selectedWabaGroups/);
assert.match(builder, /portfolioOptions/);
assert.match(builder, /selectPortfolio/);
assert.match(builder, /availableSlotsForPortfolio/);
assert.match(builder, /targets: selectedSlots\.map/);
assert.match(builder, /Resultado de creación por WABA/);
assert.match(builder, /summary\?\.duplicates/);
assert.match(builder, /function getTemplateContentPreview/);
assert.match(builder, /<p className="text-\[10px\] font-extrabold uppercase tracking-wider text-gray-400">Mensaje<\/p>/);
assert.match(builder, /contentPreview\.body/);

assert.match(esLocale, /"dash\.nav\.templates": "Generar templates"/);
assert.match(esLocale, /"templates\.builder\.title": "Constructor de templates"/);
assert.match(esLocale, /"templates\.builder\.loading_slots": "Buscando numeros Meta oficiales\.\.\."/);
assert.match(esLocale, /"templates\.builder\.access_lost_title": "La conexion con Meta perdio permisos"/);
assert.match(esLocale, /"templates\.builder\.access_lost_action_clear": "Pulsa Limpiar en la configuracion del numero para quitar la vinculacion anterior\."/);
assert.match(esLocale, /"templates\.builder\.variable_mapper": "Mapeador de variables GHL"/);
assert.match(esLocale, /"templates\.builder\.selected_ghl_variable": "Variable GHL seleccionada"/);
assert.match(enLocale, /"dash\.nav\.templates": "Generate templates"/);
assert.match(enLocale, /"templates\.builder\.title": "Template builder"/);
assert.match(enLocale, /"templates\.builder\.loading_slots": "Searching official Meta numbers\.\.\."/);
assert.match(enLocale, /"templates\.builder\.access_lost_title": "The Meta connection lost permissions"/);
assert.match(enLocale, /"templates\.builder\.access_lost_action_clear": "Click Clear in the number settings to remove the previous connection\."/);
assert.match(enLocale, /"templates\.builder\.variable_mapper": "GHL variable mapper"/);
assert.match(enLocale, /"templates\.builder\.selected_ghl_variable": "Selected GHL variable"/);

console.log("testOfficialTemplateBuilder passed");
