export const BASE_AGENT_MODEL_OPTIONS = [
  { value: 'gpt-5.2', labelKey: 'workflow_agents.model_option_gpt52' },
  { value: 'gpt-5.2-pro', labelKey: 'workflow_agents.model_option_gpt52_pro' },
  { value: 'gpt-5.1', labelKey: 'workflow_agents.model_option_gpt51' },
  { value: 'gpt-5-pro', labelKey: 'workflow_agents.model_option_gpt5_pro' },
  { value: 'gpt-5', labelKey: 'workflow_agents.model_option_gpt5' },
  { value: 'gpt-5-mini', labelKey: 'workflow_agents.model_option_gpt5_mini' },
  { value: 'gpt-5-nano', labelKey: 'workflow_agents.model_option_gpt5_nano' },
  { value: 'gpt-4.1', labelKey: 'workflow_agents.model_option_gpt41' },
  { value: 'gpt-4.1-mini', labelKey: 'workflow_agents.model_option_gpt41_mini' },
  { value: 'gpt-4.1-nano', labelKey: 'workflow_agents.model_option_gpt41_nano' },
  { value: 'o3', labelKey: 'workflow_agents.model_option_o3' },
  { value: 'o3-pro', labelKey: 'workflow_agents.model_option_o3_pro' },
  { value: 'o4-mini', labelKey: 'workflow_agents.model_option_o4_mini' },
  { value: 'o3-mini', labelKey: 'workflow_agents.model_option_o3_mini' },
  { value: 'o1', labelKey: 'workflow_agents.model_option_o1' },
  { value: 'o1-pro', labelKey: 'workflow_agents.model_option_o1_pro' },
  { value: 'gpt-4o', labelKey: 'workflow_agents.model_option_gpt4o' },
  { value: 'gpt-4o-mini', labelKey: 'workflow_agents.model_option_gpt4o_mini' },
  { value: 'gpt-4-turbo', labelKey: 'workflow_agents.model_option_gpt4_turbo' },
  { value: 'gpt-4', labelKey: 'workflow_agents.model_option_gpt4' },
  { value: 'gpt-3.5-turbo', labelKey: 'workflow_agents.model_option_gpt35_turbo' },
];
